name: Delete github repositories

on:
  push:
    branches: main

jobs:
  build-fastapi-app:
    name: Delete repositories
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      actions: read
      checks: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Delete repositories
        run: |
          python delete_repos.py ${{ vars.ORGANIZATION }} ${{ secrets.GITHUB_TOKEN }}
